DROP INDEX IF EXISTS countries_IDCountry_IDX;
DROP INDEX IF EXISTS countries_Name_IDX;
DROP INDEX IF EXISTS languages_IDLanguage_IDX;
DROP INDEX IF EXISTS languages_Name_IDX;
DROP INDEX IF EXISTS codecs_IDCodec_IDX;
DROP INDEX IF EXISTS codecs_Name_IDX;
DROP INDEX IF EXISTS tags_IDTag_IDX;
DROP INDEX IF EXISTS tags_Name_IDX;
DROP INDEX IF EXISTS stations_IDStation_IDX;
DROP INDEX IF EXISTS stations_StationUUID_IDX;
DROP INDEX IF EXISTS stations_URL_IDX;
DROP INDEX IF EXISTS stations_IDCountry_IDX;
DROP INDEX IF EXISTS stations_IDLanguage_IDX;
DROP INDEX IF EXISTS stations_Votes_IDX;
DROP INDEX IF EXISTS stations_IDCodec_IDX;
DROP INDEX IF EXISTS stations_Bitrate_IDX;
DROP INDEX IF EXISTS stations_LastCheckOK_IDX;
DROP INDEX IF EXISTS stationstags_IDStationTag_IDX;
DROP INDEX IF EXISTS stationstags_IDStation_IDX;
DROP INDEX IF EXISTS stationstags_IDTag_IDX;
CREATE UNIQUE INDEX IF NOT EXISTS countries_IDCountry_IDX ON countries (IDCountry);
CREATE INDEX IF NOT EXISTS countries_Name_IDX ON countries (Name);
CREATE UNIQUE INDEX IF NOT EXISTS languages_IDLanguage_IDX ON languages (IDLanguage);
CREATE INDEX IF NOT EXISTS languages_Name_IDX ON languages (Name);
CREATE UNIQUE INDEX IF NOT EXISTS codecs_IDCodec_IDX ON codecs (IDCodec);
CREATE INDEX IF NOT EXISTS codecs_Name_IDX ON codecs (Name);
CREATE UNIQUE INDEX IF NOT EXISTS tags_IDTag_IDX ON tags (IDTag);
CREATE INDEX IF NOT EXISTS tags_Name_IDX ON tags (Name);
CREATE UNIQUE INDEX IF NOT EXISTS stations_IDStation_IDX ON stations (IDStation);
CREATE INDEX IF NOT EXISTS stations_StationUUID_IDX ON stations (stationuuid);
CREATE INDEX IF NOT EXISTS stations_URL_IDX ON stations (url);
CREATE INDEX IF NOT EXISTS stations_IDCountry_IDX ON stations (IDCountry);
CREATE INDEX IF NOT EXISTS stations_IDLanguage_IDX ON stations (IDLanguage);
CREATE INDEX IF NOT EXISTS stations_Votes_IDX ON stations (votes);
CREATE INDEX IF NOT EXISTS stations_IDCodec_IDX ON stations (IDCodec);
CREATE INDEX IF NOT EXISTS stations_Bitrate_IDX ON stations (bitrate);
CREATE INDEX IF NOT EXISTS stations_LastCheckOK_IDX ON stations (lastcheckok);
CREATE UNIQUE INDEX IF NOT EXISTS stationstags_IDStationTag_IDX ON stationstags (IDStationTag);
CREATE INDEX IF NOT EXISTS stationstags_IDStation_IDX ON stationstags (IDStation);
CREATE INDEX IF NOT EXISTS stationstags_IDTag_IDX ON stationstags (IDTag);